config/routes.rb
Rails.application.routes.draw do 
  #yehtetaung start 24/6/2019
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  #yehtetaung end 24/6/2019
  
  #yehtetaung start 26/6/2019
  get '/search', to: 'sessions#search'
  post '/search', to: 'sessions#wsearch'
  #yehtetaung end 1/7/2019
  
  #yehtetaung start 24/6/2019
  root 'static_pages#welcome' 
  #yehtetaung end 24/6/2019

  #yehtetaung start 25/6/2019
  get '/workspacecreate', to: 'static_pages#workspacecreate'
  get '/workspacehome', to: 'static_pages#workspacehome'
  #yehtetaung end 25/6/2019

  #Thinzarthein,SweZinMyat start 24/6/2019
  get '/home', to:'static_pages#home'
  #Thinzarthein,SweZinMyat end 25/6/2019
 
  #SweZinMyat start 5/7/2019
  get '/unread', to: 'static_pages#unread'
  get '/update', to: 'static_pages#update'
  #SweZinMyat end 8/7/2019

  #yehtetaung start 24/6/2019
  get '/signup', to:'users#new'
  post '/signup',to: 'users#create'
  #yehtetaung end 24/6/2019
 
  #yehtetaung start 25/6/2019
  post '/wscreate', to: 'workspace#create'
  get '/wscreate' , to: 'workspace#new'
  #yehtetaung end 25/6/2019
  
  #shinehtetnaung start 25/6/2019
  get '/managemember', to: 'channel#managemember'
  delete '/userremove', to: 'channel#userremove'
  #shinehtetnaung start 28/6/2019

  #Thinzarthein start 17/7/2019
  get '/managechannel', to: 'channel#managechannel'
  delete '/channeldelete', to: 'channel#channeldelete'
  #Thinzarthein end 17/7/2019
  
  #shinehtetnaung start 24/6/2019
  get '/channel', to: 'channel#new'
  post '/channel', to: 'channel#create'
  #shinehtetnaung end 25/6/2019
  
  #Thinzarthein start 26/6/2019
  get '/channelchat', to: 'channel#channelchat'
  get '/memberedit', to: 'channel#memberedit'
  get '/chmemberinvite', to: 'channel#chmemberinvite'
  get '/addchmember', to: 'channel#addchmember'
  delete '/channelremove',to: 'channel#channelremove'
  get '/chreplymsg', to: 'chmsgthread#chreplymsg'
  #Thinzarthein end 3/7/2019
  
  #Thinzarthein,SweZinMyat start 2/7/2019
  post '/chmessage' , to: 'channel#message'
  delete '/chmessagedelete', to:'channel#chmessagedelete'
  #Thinzarthein,SweZinMyat end 4/7/2019
  
  #Eishwezinhtun,yehtetaung  start 25/6/2019
  get '/mention', to: 'channel#mention'
  #Eishwezinhtun,yehtetaung end 12/7/2019
  
  #SweZinMyat start 5/7/2019
  get '/chmsgthread', to: 'chmsgthread#new'
  post '/chthreadinsert', to: 'chmsgthread#chthreadinsert'
  get  '/thread', to: 'threads#new'
  get '/dirmsgthread', to: 'dirmsgthread#new'
  post '/dirthreadinsert', to: 'dirmsgthread#dirthreadinsert'
  #SweZinMyat end 8/7/2019

  #Thinzarthein,SweZinMyat start 26/6/2019
  get  '/dirmsg',  to:'directmessage#new'
  post '/dirmsgcreate', to:'directmessage#create'
  delete '/messagedelete', to:'directmessage#messagedelete'
  #Thinzarthein,SweZinMyat start 1/7/2019

  #Thinzarthein start  10/7/2019
  get '/replymsg', to: 'dirmsgthread#replymsg'
  #Thinzarthein end 10/7/2019
  
  #SweZinMyat start 25/7/2019
  get '/dirmsgstar', to: 'dirmsgstar#new'
  delete '/dirmsgunstar', to: 'dirmsgstar#dirunstar'
  get '/chmsgstar', to: 'chmsgstar#new'
  delete '/chmsgunstar', to: 'chmsgstar#chunstar'
  get '/starmessage', to: 'static_pages#starmessage'
  get '/pubchannelshow', to: 'channel#pubchannelshow'
  get '/pubchmember', to: 'channel#pubchmember'
  #SweZinMyat start 16/7/2019

  #shinehtetnaung start 1/7/2019
  get '/invitations', to:'invitations#invitemember'
  post '/invitations', to:'invitations#create' 
  get '/invite', to: 'joinmembers#new'
  post '/invite', to: 'joinmembers#create' 
  #shinehtetnaung start 8/7/2019

  resources :invitations,only: [:create]
  resources :joinmembers
  
end

app/controllers/static_pages_controller.rb
require "will_paginate/array"
class StaticPagesController < ApplicationController
  #To show welcome page
  def welcome
  end

  def workspacehome
  end

  def workspacecreate
  end

  #To show home page
  def home
    main
    #@pubarray = Array.new
    #@m_channel.each { |r|
      #@pubarray.push(r.channel_name)
    #}
    #@public_channel_list = MChannel.select("distinct m_channels.channel_name,m_channels.channel_id")
                                   #.joins("join m_workspaces on m_workspaces.workspace_id = m_channels.workspace_id  ")
                                   #.where(" m_channels.status=1 and m_workspaces.workspace_id=? and m_channels.user_id!=?", session[:workspace_id], session[:user_id])
  end

  #To update is_read's value 1 to 0 into t_dirmessages and t_chunread_messages
  def update
    TDirmessage.where("receiver_user_id=? and dirworkspace_id=?", session[:user_id], session[:workspace_id]).update_all(is_read: 0)
    TChunreadMessage.joins("join t_channel_messages on t_channel_messages.chmsg_id=t_chunread_messages.chmsg_id")
                    .where("chuser_id=? ", session[:user_id]).update_all(is_read: 0)
    redirect_back(fallback_location: update_path)
  end

  #star button for showing starmessages
  def starmessage
    main
    @dstar = TDirmessage.select("m_users.user_name,t_dirmessages.dir_message,t_dirmessages.created_at")
                        .joins("join m_users on m_users.user_id=t_dirmessages.sender_user_id join t_directstars on t_directstars.stardimsg_id=t_dirmessages.dirmsg_id")
                        .where("dirworkspace_id=? and t_directstars.star_userid=?", session[:workspace_id], session[:user_id]).order("t_dirmessages.created_at ASC")
    @dstar = @dstar.paginate(page: params[:page], per_page: 3)

    #@dirmesg = TDirmessage.select("m_users.user_name,t_dirmessages.dir_message,t_dirmessages.created_at")
                          #.joins("join m_users on m_users.user_id=t_dirmessages.sender_user_id")
                          #.where("dirworkspace_id=? and ((receiver_user_id=? and sender_user_id=?)||(t_dirmessages.receiver_user_id=? and t_dirmessages.sender_user_id=?))", session[:workspace_id], session[:user_id], params[:clickuserid], params[:clickuserid], session[:user_id]).order("t_dirmessages.created_at ASC")
    @clickchannel = MChannel.find_by("channel_id=?", session[:clickchannel_id])
    #@star = TChannelMessage.select("m_users.user_name,t_dirmessages.dir_message,t_dirmessages.created_at")
                           #.joins("join m_users on m_users.user_id=t_dirmessages.sender_user_id join t_directstars on t_directstars.stardimsg_id=t_dirmessages.dirmsg_id")
                           #.where("dirworkspace_id=? and t_directstars.star_userid=?", session[:workspace_id], session[:user_id]).order("t_dirmessages.created_at ASC")
    @chstar = TChannelMessage.select("m_channels.channel_name ,m_users.user_name ,t_channel_messages.chmessage,t_channel_messages.created_at")
                             .joins("join m_users on t_channel_messages.chsender_id=m_users.user_id join t_chmsgstars on t_chmsgstars.chmsgstarid=t_channel_messages.chmsg_id join m_channels on m_channels.channel_id=t_channel_messages.channel_id")
                             .where(" t_chmsgstars.chstar_userid=? and m_channels.user_id = ? and m_channels.workspace_id=? ", session[:user_id], session[:user_id], session[:workspace_id])
    @chstar = @chstar.paginate(page: params[:page], per_page: 3)
  end

  #for showing unread messages, when click unread button
  def unread
    home
    #@dirmesg = TDirmessage.select("m_users.user_name,t_dirmessages.dir_message,t_dirmessages.created_at")
                          #.joins("join m_users on m_users.user_id=t_dirmessages.sender_user_id")
                          #.where("dirworkspace_id=? and ((receiver_user_id=? and sender_user_id=?)||(t_dirmessages.receiver_user_id=? and t_dirmessages.sender_user_id=?))", session[:workspace_id], session[:user_id], params[:clickuserid], params[:clickuserid], session[:user_id]).order("t_dirmessages.created_at ASC")
    @clickchannel = MChannel.find_by("channel_id=?", session[:clickchannel_id])

    @m_clickchuser = MUser.joins("join m_channels on m_channels.user_id=m_users.user_id")
                          .where("m_channels.channel_name=? and m_channels.workspace_id=?", session[:clickchannel_name], session[:workspace_id])

    @dirmsg = TDirmessage.select("m_users.user_name,t_dirmessages.dir_message,t_dirmessages.created_at")
                         .joins("join m_users on m_users.user_id=t_dirmessages.sender_user_id")
                         .where("dirworkspace_id=? and receiver_user_id=? and is_read=1", session[:workspace_id], session[:user_id])
    @chmesg = TChannelMessage.select("m_channels.channel_name ,m_users.user_name ,t_channel_messages.chmessage,t_channel_messages.created_at")
                             .joins("join m_users on t_channel_messages.chsender_id=m_users.user_id join t_chunread_messages on t_chunread_messages.chmsg_id=t_channel_messages.chmsg_id join m_channels on m_channels.channel_id=t_channel_messages.channel_id")
                             .where("t_chunread_messages.is_read =1 and t_chunread_messages.chuser_id=? and m_channels.user_id=? and m_channels.workspace_id=? ", session[:user_id], session[:user_id], session[:workspace_id])
  end
end

app/views/static_pages/home.html.erb
<%= render 'pannel/nav' %>
<div class="main">
  <div class="header",style="margin-top:0px">
    <div class="col-md-4 col-md-offset-4" style="font-size:30px;color:pink;padding-top:23px">
      Home Page
     <%= session[:wrokspace_name] %>
    </div>
    <div class="col-md-2", style="float:right;padding-top:25px">
        <%= link_to "@",mention_path,class: "", style:"color:pink" %>
        <%= link_to "",starmessage_path,class: "fa fa-star-o" , style:"color:pink" %>      
    </div>    
  </div> 
  <script>
  /* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
  var dropdown = document.getElementsByClassName("dropdown-btn");
  var i;  
  for (i = 0; i < dropdown.length; i++) {
    dropdown[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var dropdownContent = this.nextElementSibling;
    if (dropdownContent.style.display === "block") {
    dropdownContent.style.display = "none";
    } else {
    dropdownContent.style.display = "block";
    }
    });
  }
  </script>
</div>
<script language="javascript" type="text/javascript">setTimeout("location.reload();",20000);</script>

app/views/static_pages/starmessage.html.erb
<%= render 'pannel/nav' %>
<div class="main">
  <div class="header">
    <div class="col-md-5 col-md-offset-5" style="font-size:30px;color:pink;padding-top:20px">
      Star
    </div>
    <div class="col-md-2", style="float:right;padding-top:25px;font-size:25px;">
        <%= link_to "",home_path,class: "fa fa-times-circle", style:"color:pink" %>
    </div>
</div>
  <div>
    <% @dstar.each do |dstar| %>
      <div class="user">
          &nbsp; <i class="fa fa-fw fa-picture-o"></i>
          &nbsp;<%= dstar.user_name%>&nbsp;&nbsp;
          <date style="font-size:18px; padding-left:20px;color:gray;">
            <%= l dstar.created_at, format: :euro  %>
          </date>
      </div>
      <div class="message" style="font-size:16px">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= dstar.dir_message %></div>       
    <%end%>
  </div>
  <div>
      <% @chstar.each do |chstar| %>
        &nbsp; <div class="fa fa-users"><%= chstar.channel_name%></div>
        <div class="user">
        &nbsp; <i class="fa fa-fw fa-picture-o"></i>
          &nbsp;<%= chstar.user_name%>&nbsp;&nbsp;
          <date style="font-size:18px; padding-left:20px;color:gray;">
            <%=  l chstar.created_at, format: :euro  %>
          </date>
        </div>
        <div class="message" style="font-size:16px">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= chstar.chmessage %></div>      
      <%end%>
  </div>
   &nbsp;<%= will_paginate @chstar, :page_links => false%>
  <script>
  /* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
  var dropdown = document.getElementsByClassName("dropdown-btn");
  var i;  
  for (i = 0; i < dropdown.length; i++) {
    dropdown[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var dropdownContent = this.nextElementSibling;
    if (dropdownContent.style.display === "block") {
    dropdownContent.style.display = "none";
    } else {
    dropdownContent.style.display = "block";
    }
    });
  }
  </script>
</div>

<script language="javascript" type="text/javascript">setTimeout("location.reload();",20000);</script>

app/views/static_pages/unread.html.erb
<%= render 'pannel/nav' %>
<div class="main">
  <div class="header">
    <div class="col-md-10" style="font-size:30px;color:pink;">
        All Unread<br>
        <p style="font-size:15px;color:white"><%=@totalcount%>messages<p>
    </div>
    <div class="col-md-2", style="float:right;font-size:25px;padding-top:25px">      
        <%= link_to "",home_path,class: "fa fa-times-circle", style:"color:pink" %>      
    </div>      
  </div>   
  <div class="content" style="width:100%">   
  <div>    
    <% @dirmsg.each do |dirmsg| %>     
     <div class="user"><i class="fa fa-fw fa-picture-o"></i>&nbsp;<%= dirmsg.user_name%>
     </div>
      <div class="message" style="font-size:16px">
         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= dirmsg.dir_message %>
         <%=  l dirmsg.created_at, format: :euro  %>
      </div>
    <%end%>
   </div>
   <br>  
    <div>
     <% @chmesg.each do |chmsg| %>
       <div class="message"><i class="fa fa-users">
         </i>&nbsp;<%= chmsg.channel_name%>
       </div>
       <div class="user"><i class="fa fa-fw fa-picture-o">
         </i>&nbsp;<%= chmsg.user_name%>
         <date style="font-size:18px; padding-left:20px;color:gray;">
              <%=  l chmsg.created_at, format: :euro  %>
         </date>
       </div>
       <div class="message" style="font-size:16px"> 
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= chmsg.chmessage %>
       </div>
     <%end%>
    </div>
  <div class="col-md-5 col-md-offset-3", style="padding-top:20px;">    
    <%= link_to "Mark all messages read",update_path,class: "btn btn-lg btn-primary", style:"background-color:#59b300;color:white" %> 
   </div>
<script>
/* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
var dropdown = document.getElementsByClassName("dropdown-btn");
var i;

for (i = 0; i < dropdown.length; i++) {
  dropdown[i].addEventListener("click", function() {
  this.classList.toggle("active");
  var dropdownContent = this.nextElementSibling;
  if (dropdownContent.style.display === "block") {
  dropdownContent.style.display = "none";
  } else {
  dropdownContent.style.display = "block";
  }
  });
}
</script>

app/views/static_pages/welcome.html.erb
<header>
<nav class="navbar navbar-light bg-red">
 <a class="navbar-brand col-md-10" href="/" style="font-size:30px;">Slack App</a>
 <ul class="nav navbar-nav navbar-right col-md-2">
         <div style="padding-top:30px;padding-left:100px;">
            <button class="btn btn-outline-success" type="button"><%= link_to "Log in", login_path %> 
            </button>
         </div>
  </ul>
</nav>
</header> 
<div class="center jumbotron">
  <h1>Welcome to Slack_App</h1>
  <br><br><br><br><br>
  <div class="col-md-5 col-md-offset-5">  
  <%= link_to "Sign Up",signup_path, class: "btn btn-lg btn-primary" %>  
  </div>
  <br><br>
</div>

app/views/static_pages/workspacecreate.html.erb
<div class="container wframe">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <%= link_to "WorkSpace Create", wscreate_path, class: "btn btn-lg btn-primary btnW" %>
        </div>
    </div> 
</div>

app/views/static_pages/workspacehome.html.erb
<div class="container wframe">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <%= link_to "WorkSpace Create", wscreate_path, class: "btn btn-lg btn-primary btnW" %>
        </div>
    </div> 
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <%= link_to "Search Your WorkSpace", search_path, class: "btn btn-lg btn-primary btnW" %>
        </div>
    </div> 
</div>