config/routes.rb
Rails.application.routes.draw do 
  #yehtetaung start 24/6/2019
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  #yehtetaung end 24/6/2019
  
  #yehtetaung start 26/6/2019
  get '/search', to: 'sessions#search'
  post '/search', to: 'sessions#wsearch'
  #yehtetaung end 1/7/2019
  
  #yehtetaung start 24/6/2019
  root 'static_pages#welcome' 
  #yehtetaung end 24/6/2019

  #yehtetaung start 25/6/2019
  get '/workspacecreate', to: 'static_pages#workspacecreate'
  get '/workspacehome', to: 'static_pages#workspacehome'
  #yehtetaung end 25/6/2019

  #Thinzarthein,SweZinMyat start 24/6/2019
  get '/home', to:'static_pages#home'
  #Thinzarthein,SweZinMyat end 25/6/2019
 
  #SweZinMyat start 5/7/2019
  get '/unread', to: 'static_pages#unread'
  get '/update', to: 'static_pages#update'
  #SweZinMyat end 8/7/2019

  #yehtetaung start 24/6/2019
  get '/signup', to:'users#new'
  post '/signup',to: 'users#create'
  #yehtetaung end 24/6/2019
 
  #yehtetaung start 25/6/2019
  post '/wscreate', to: 'workspace#create'
  get '/wscreate' , to: 'workspace#new'
  #yehtetaung end 25/6/2019
  
  #shinehtetnaung start 25/6/2019
  get '/managemember', to: 'channel#managemember'
  delete '/userremove', to: 'channel#userremove'
  #shinehtetnaung start 28/6/2019

  #Thinzarthein start 17/7/2019
  get '/managechannel', to: 'channel#managechannel'
  delete '/channeldelete', to: 'channel#channeldelete'
  #Thinzarthein end 17/7/2019
  
  #shinehtetnaung start 24/6/2019
  get '/channel', to: 'channel#new'
  post '/channel', to: 'channel#create'
  #shinehtetnaung end 25/6/2019
  
  #Thinzarthein start 26/6/2019
  get '/channelchat', to: 'channel#channelchat'
  get '/memberedit', to: 'channel#memberedit'
  get '/chmemberinvite', to: 'channel#chmemberinvite'
  get '/addchmember', to: 'channel#addchmember'
  delete '/channelremove',to: 'channel#channelremove'
  get '/chreplymsg', to: 'chmsgthread#chreplymsg'
  #Thinzarthein end 3/7/2019
  
  #Thinzarthein,SweZinMyat start 2/7/2019
  post '/chmessage' , to: 'channel#message'
  delete '/chmessagedelete', to:'channel#chmessagedelete'
  #Thinzarthein,SweZinMyat end 4/7/2019
  
  #Eishwezinhtun,yehtetaung  start 25/6/2019
  get '/mention', to: 'channel#mention'
  #Eishwezinhtun,yehtetaung end 12/7/2019
  
  #SweZinMyat start 5/7/2019
  get '/chmsgthread', to: 'chmsgthread#new'
  post '/chthreadinsert', to: 'chmsgthread#chthreadinsert'
  get  '/thread', to: 'threads#new'
  get '/dirmsgthread', to: 'dirmsgthread#new'
  post '/dirthreadinsert', to: 'dirmsgthread#dirthreadinsert'
  #SweZinMyat end 8/7/2019

  #Thinzarthein,SweZinMyat start 26/6/2019
  get  '/dirmsg',  to:'directmessage#new'
  post '/dirmsgcreate', to:'directmessage#create'
  delete '/messagedelete', to:'directmessage#messagedelete'
  #Thinzarthein,SweZinMyat start 1/7/2019

  #Thinzarthein start  10/7/2019
  get '/replymsg', to: 'dirmsgthread#replymsg'
  #Thinzarthein end 10/7/2019
  
  #SweZinMyat start 25/7/2019
  get '/dirmsgstar', to: 'dirmsgstar#new'
  delete '/dirmsgunstar', to: 'dirmsgstar#dirunstar'
  get '/chmsgstar', to: 'chmsgstar#new'
  delete '/chmsgunstar', to: 'chmsgstar#chunstar'
  get '/starmessage', to: 'static_pages#starmessage'
  get '/pubchannelshow', to: 'channel#pubchannelshow'
  get '/pubchmember', to: 'channel#pubchmember'
  #SweZinMyat start 16/7/2019

  #shinehtetnaung start 1/7/2019
  get '/invitations', to:'invitations#invitemember'
  post '/invitations', to:'invitations#create' 
  get '/invite', to: 'joinmembers#new'
  post '/invite', to: 'joinmembers#create' 
  #shinehtetnaung start 8/7/2019

  resources :invitations,only: [:create]
  resources :joinmembers
  
end

app/controllers/channel_controller.rb
class ChannelController < ApplicationController
  #To create new channel
  def new
    @channel = MChannel.new
  end

  #To manage users from current workspace
  def managemember
    main
    @curchuser = MUser.select("*")
      .joins("join m_workspaces on m_workspaces.user_id = m_users.user_id")
      .where("m_workspaces.workspace_id= ?", session[:workspace_id]).paginate(page: params[:page], per_page: 3)
  end

  #click add button for insert users into m_channels table
  def addchmember
    @channel = MChannel.new
    @channel.channel_id = session[:clickchannel_id]
    @channel.channel_name = session[:clickchannel_name]
    @channel.user_id = params[:linkuser]
    @channel.workspace_id = session[:workspace_id]
    @channel.status = session[:clickchannel_status]
    @channel.chadmin = 0
    @channel.save
    redirect_to memberedit_path
  end

  #To show all users that does not exist in current channel from current workspace
  def chmemberinvite
    @clickchannel = MChannel.find_by("channel_id=?", session[:clickchannel_id])
    managemember
    @temp_channel = MUser.select("m_users.user_id")
                         .joins("join m_channels on m_channels.user_id=m_users.user_id")
                         .where("m_channels.channel_name=? and m_channels.workspace_id=?", session[:clickchannel_name], session[:workspace_id])
    @arychannel = Array.new
    @temp_channel.each { |r|
      @arychannel.push(r.user_id)
    }
    @count = MChannel.select("*")
                     .where("workspace_id=? and channel_id=?", session[:workspace_id], session[:clickchannel_id])
    @currentcount = (@count.size).to_s
  end

  #To remove the users that exist in current channel
  def channelremove
    MChannel.find_by("user_id=? and channel_id=?", params[:removeuser], session[:clickchannel_id]).delete
    redirect_to memberedit_path
  end

  #To delete users that exist in current workspace
  def userremove
    MWorkspace.find_by("user_id=? and workspace_id=?", params[:userremove], session[:workspace_id]).delete
    redirect_to managemember_path
  end

  #To delete channel from m_channels table
  def channeldelete
    MChannel.find_by("channel_id=? ", params[:channelremove]).delete
    redirect_to managechannel_path
  end

  #To show current channel messages
  def channelchat
    @clickchannel = MChannel.find_by("channel_id=?", params[:clickchannelid])
    clickchannel @clickchannel
    TChunreadMessage.joins("join t_channel_messages on t_channel_messages.chmsg_id=t_chunread_messages.chmsg_id")
                    .where("chuser_id=?  and t_channel_messages.channel_id =? ", session[:user_id], @clickchannel.channel_id)
                    .update_all(is_read: 0)
    main
    @chmesg = TChannelMessage.select("m_users.user_name,t_channel_messages.chmsg_id,t_channel_messages.count,t_channel_messages.chmessage,t_channel_messages.created_at,t_channel_messages.updated_at")
                             .joins("join m_users on m_users.user_id=t_channel_messages.chsender_id")
                             .where("channel_id=?", session[:clickchannel_id]).order("t_channel_messages.created_at ASC")
    @chmesg.each { |thread|
      @thredcount = HChmessageReply.select("*")
                                   .joins("join t_channel_messages on t_channel_messages.chmsg_id=h_chmessage_replies.chmsgid")
                                   .where("h_chmessage_replies.chmsgid=?", thread.chmsg_id)
      thread.count = (@thredcount.size).to_s
    }
    @chstar = TChmsgstar.select("t_chmsgstars.chmsgstarid")
                        .joins("join t_channel_messages on t_chmsgstars.chmsgstarid=t_channel_messages.chmsg_id")
                        .where("channel_id=? and t_chmsgstars.chstar_userid=?", session[:clickchannel_id], session[:user_id])
    @charray = Array.new
    @chstar.each { |r|
      @charray.push(r.chmsgstarid)
    }
    @muser = MUser.select("m_users.user_id, m_users.user_name")
                  .joins("join m_channels on m_users.user_id=m_channels.user_id ")
                  .where("m_channels.channel_id=? and m_users.user_id !=?", session[:clickchannel_id], session[:user_id])
  end

  #To edit the users (add or remove)
  def memberedit
    main
    @clickchannel = MChannel.find_by("channel_id=?", session[:clickchannel_id])
    @m_clickuser = MUser.select("*").joins("join m_channels on m_channels.user_id=m_users.user_id").where("m_channels.channel_name=? and m_channels.workspace_id=?", session[:clickchannel_name], session[:workspace_id])
    #@count = MChannel.select("*").where("workspace_id=? and channel_name=?",session[:workspace_id],session[:clickchannel_name])
    #@currentcount = (@count.size).to_s
    @count = MChannel.select("*")
                     .where("workspace_id=? and channel_id=?", session[:workspace_id], session[:clickchannel_id])
    @chmembercount = (@count.size).to_s
    @chadmin = MChannel.select("*")
                       .joins("join m_users on m_channels.user_id=m_users.user_id")
                       .where("m_channels.channel_name=? and m_channels.workspace_id=? and m_channels.chadmin = 1", session[:clickchannel_name], session[:workspace_id])
    @chnotadmin = MChannel.select("*")
                          .joins("join m_users on m_channels.user_id=m_users.user_id")
                          .where("m_channels.channel_name=? and m_channels.workspace_id=? and m_channels.chadmin != 1", session[:clickchannel_name], session[:workspace_id])

    @chnotadmin = @chnotadmin.paginate(page: params[:page], per_page: 10)
  end

  #for messages send button
  def message
    mention_name = params[:channel][:memtion_name]
    mention_name[0] = ""
    mention_u = MUser.find_by(user_name: mention_name)

    @t_chmsg = TChannelMessage.new

    @t_chmsg.chsender_id = session[:user_id]
    @t_chmsg.channel_id = session[:clickchannel_id]
    @t_chmsg.chmessage = params[:channel][:chmessage]
    if mention_u
      @t_mention = TMention.new
      @t_mention.mentioned_id = mention_u.user_id
      @t_mention.login_user_id = session[:user_id]
      @t_mention.workspace_id = session[:workspace_id]
      @t_mention.mention_message = params[:channel][:chmessage]
      @t_mention.chmsgmen_id = session[:clickchannel_id]
      @t_mention.save
    end
    @t_chmsg.save
    main
    @chmsg = TChannelMessage.find_by("chsender_id=? and channel_id=? and chmessage=?", session[:user_id], @t_chmsg.channel_id, @t_chmsg.chmessage)
    @clickchannel = MChannel.find_by("channel_id=?", session[:clickchannel_id])
    @m_clickuser = MUser.joins("join m_channels on m_channels.user_id=m_users.user_id")
                        .where("m_channels.channel_name=? and m_channels.workspace_id=?", session[:clickchannel_name], session[:workspace_id])
    @m_clickuser.each { |chuser|
      @tchmsg = TChunreadMessage.new
      @tchmsg.chmsg_id = @chmsg.chmsg_id
      @tchmsg.chuser_id = chuser.user_id
      if chuser.user_id == session[:user_id]
        @tchmsg.is_read = 0
      else
        @tchmsg.is_read = 1
      end
      @tchmsg.save
    }
    redirect_back(fallback_location: chmessage_path)
  end

  #To delete channel messages
  def chmessagedelete
    TChannelMessage.where("chmsg_id=?", params[:messagedelete]).delete_all
    redirect_back(fallback_location: chmessage_path)
  end

  #To show mention users who was mentioned log-in user
  def mention
    memberedit
    @men = TMention.select("*")
                   .joins("join m_users on m_users.user_id=t_mentions.login_user_id join m_channels on m_channels.channel_id=t_mentions.chmsgmen_id")
                   .where("t_mentions.mentioned_id=? and t_mentions.workspace_id=? and m_channels.user_id=?", session[:user_id], session[:workspace_id], session[:user_id])
  end

  #To manage channel from current workspace
  def managechannel
    main
    #@chmesg=TChannelMessage.select("*").joins("join m_users on m_users.user_id=t_channel_messages.chsender_id").where("channel_id=?",session[:clickchannel_id]).order("t_channel_messages.created_at ASC")
    @curworchannel = MChannel.joins("join m_workspaces on m_workspaces.workspace_id = m_channels.workspace_id and m_channels.user_id = m_workspaces.user_id ")
      .where("m_workspaces.workspace_id=? and m_channels.user_id=? and m_channels.chadmin= 1", session[:workspace_id], session[:user_id])
    @curworchannel = @curworchannel.paginate(page: params[:page], per_page: 13)
  end

  #To create new channel
  def create
    @channel = MChannel.new()
    if params[:session][:channelname].blank?
      flash[:danger] = "Write your channel name!"
      redirect_to channel_path
    else
      @channel.user_id = session[:user_id]
      @channel.workspace_id = session[:workspace_id]
      @channel.channel_name = params[:session][:channelname]
      @channel.chadmin = 1
      if params[:channeltype] == "private"
        @channel.status = 0
      else
        @channel.status = 1
      end
      @w = MChannel.select("*").where("workspace_id=?", session[:workspace_id])
      @ary = Array.new
      @w.each { |w|
        @ary.push(w.channel_name)
      }
      if !@ary.include?(params[:session][:channelname])
        @channel.save
        redirect_to home_path
      else
        flash[:danger] = "Channel Name is already taken!"
        redirect_to channel_path
      end
    end
  end

  def pubchannelshow
    channelchat
  end

  def pubchmember
    memberedit
  end
end

app/helpers/channel_helper.rb
module ChannelHelper
end

app/views/channel/channelchat.html.erb
<%= render 'pannel/nav' %>
<div class="main">
<div class="header">
    <div class="col-md-10" style="font-size:20px;color:pink;padding-top:20px">
      <div class="fa fa-users"> <%= session[:clickchannel_name]%></div><br>
      <%= link_to "Member List",memberedit_path, style:"color:#59b300" %>
    </div>
    <div class="col-md-2", style="float:right;padding-top:30px">
        <%= link_to "",home_path, class:"fa fa-times-circle", style:"color:pink"%>
    </div>
  </div>
  <div class="content">
    <% @chmesg.each do |chmsg|%>
          <div class="dropdown-container2">
            <div class="user"><i class="fa fa-fw fa-picture-o"></i>&nbsp;<%= chmsg.user_name %>
             <date style="font-size:18px; padding-left:20px;color:gray;"> <%=  l chmsg.created_at, format: :euro  %><br></date>
            </div>
            <div class="col-md-12 message" style="font-size:16px"> 
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <%= chmsg.chmessage %>
              <%= link_to "",chmessagedelete_path(messagedelete:chmsg.chmsg_id),:method => :delete , class: "fa fa-trash", style: "color:pink"%>
              <% if @charray.include?(chmsg.chmsg_id)%>
                <%= link_to"",chmsgunstar_path(:clickchid => session[:clickchannel_id],:unchstarid => chmsg.chmsg_id),:method => :delete,class:"fa fa-star",style:"color:pink"%>
              <%else%>
               <%= link_to "",chmsgstar_path(:clickchstarid => chmsg.chmsg_id),class:"fa fa-star-o",style:"color:pink"%>
              <%end%>
              <%if chmsg.count != 0 %>
                <%=chmsg.count%><%= link_to "replies",chreplymsg_path(chclickid:chmsg.chmsg_id),class:"",style:"color:pink"%>
              <%end%>
              <%= link_to "",chmsgthread_path(chthread_id:chmsg.chmsg_id) , class: "fa fa-comment-o", style: "color:pink"%>
              <br>
            </div>
          </div>
    <%end%> 
  </div>
   <div class="footer">
    <div class="col-md-8 col-md-offset-2", style="margin-top:20px">
    <%= form_for(:channel, url:chmessage_path) do |f| %>
      <div class="col-md-10">
      <%= f.text_field :chmessage, class: 'form-control',data: { autocomplete_source: @muser.order(:user_name).map { |t| 
      { :label => '@' + t.user_name} } }, id: 'autocomplete-4' %>
      </div>
      <div class="col-md-2">
      <%= f.submit "Send", class: "btn btn-primary" %>
      <%= f.hidden_field :memtion_name, class: 'memtion_name' %>
      </div>
      <% end %>
      </div>
  </div>
  <script>
    $( "#autocomplete-4" ).autocomplete({
      source: $('#autocomplete-4').data('autocomplete-source'),
      position: {
        my: "left bottom",
        at: "left top",
      },
    select: function(event, ui) {
      event.preventDefault();
      this.value = ui.item.label
      $('.memtion_name').val(ui.item.value)
    }
    });
 </script>
  <script>
    $('.content').scrollTop($('.content')[0].scrollHeight);
    /* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
    var dropdown = document.getElementsByClassName("dropdown-btn");
    var i;
  
    for (i = 0; i < dropdown.length; i++) {
    dropdown[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var dropdownContent = this.nextElementSibling;
    if (dropdownContent.style.display === "block") {
    dropdownContent.style.display = "none";
    } else {
    dropdownContent.style.display = "block";
    }
    });
   }
  </script>
</div>

 <script language="javascript" type="text/javascript">setTimeout("location.reload();",20000);</script>

app/views/channel/chmemberinvite.html.erb
<%= render 'pannel/nav' %>
<div class="main">
  <div class="header">
    <div class="col-md-10 fa fa-users" style="font-size:20px;color:pink;padding-top:25px">
      <%= @clickchannel.channel_name %><br>
    </div>
    <div class="col-md-2", style="float:right;padding-top:30px">
        <%= link_to "",memberedit_path, class:"fa fa-times-circle", style:"color:pink"%>
    </div>
  </div>
  <div class="member_edit">
      <div class="col-md-4"><i class="fa fa-fw fa-users"></i><%="Member Add"%></div>
        &nbsp
      <% @curchuser.each do|user|%>
        &nbsp 
      <% unless @arychannel.include?(user.user_id)%>
        <div class="user_remove">    
          <div class="col-md-4">
            <i class="fa fa-fw fa-circle" style="color:green;font-size:18px;"></i>
            <%= user.user_name %>
          </div>
          <div class="col-md-2" style="color:black">
            <%= link_to "", addchmember_path(linkuser:user.user_id),class:"fa fa-plus-circle" %>
          </div>
        </div> 
      <% end %>
    <%end%>
  </div>
  <script>
  /* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
  var dropdown = document.getElementsByClassName("dropdown-btn");
  var i;
  
  for (i = 0; i < dropdown.length; i++) {
    dropdown[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var dropdownContent = this.nextElementSibling;
    if (dropdownContent.style.display === "block") {
    dropdownContent.style.display = "none";
    } else {
    dropdownContent.style.display = "block";
    }
    });
  }
  </script>
</div>

app/views/channel/managechannel.html.erb
<%= render 'pannel/nav' %>
<div class="main">
  <div class="header" style="padding-top:20px">
    <div class="col-md-4 col-md-offset-4" style="font-size:28px;color:pink;">
       Channel Management
    </div>    
    <div class="col-md-2", style="float:right">      
        <%= link_to "",home_path, class:"fa fa-times-circle", style:"color:pink"%>      
    </div>
  </div>  
  <br> 
       <div class="col-md-4 col-md-offset-4">
         <% @curworchannel.each do|channel|%>
          <i class="fa fa-users"></i>
          <%=channel.channel_name%>
          <%= link_to "Delete",channeldelete_path(channelremove:channel.channel_id),:method => :delete, class:"", style:"color:red" %>
         <br>
       <%end%>
       <%= will_paginate @curworchannel, :page_links => false%>
    </div>
    
  <div>
<script>
/* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
var dropdown = document.getElementsByClassName("dropdown-btn");
var i;
for (i = 0; i < dropdown.length; i++) {
  dropdown[i].addEventListener("click", function() {
  this.classList.toggle("active");
  var dropdownContent = this.nextElementSibling;
  if (dropdownContent.style.display === "block") {
  dropdownContent.style.display = "none";
  } else {
  dropdownContent.style.display = "block";
  }
  });
}
</script>

app/views/channel/managemember.html.erb
<%= render 'pannel/nav' %>
<div class="main">
  <div class="header" style="padding-top:20px">
    <div class="col-md-4 col-md-offset-4" style="font-size:28px;color:pink;">
       Member Management
    </div>
    <div class="col-md-2", style="float:right">
        <%= link_to "",home_path, class:"fa fa-times-circle", style:"color:pink"%>      
    </div>
 </div>    
    <br>
    <div class="col-md-4 col-md-offset-4" ><% @curchuser.each do|user|%>
       <% if user.admin != 1 %>
         <i class="fa fa-user"></i><%=user.user_name%> &nbsp;
         <%= link_to "Remove",userremove_path(userremove:user.user_id),:method => :delete, class:"", style:"color:red" %>
       <%end%>
        <br>
       <%end%>
      <%= will_paginate @curchuser, :page_links => false%>     
    </div>
</div>
  <script>
/* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
var dropdown = document.getElementsByClassName("dropdown-btn");
var i;

for (i = 0; i < dropdown.length; i++) {
  dropdown[i].addEventListener("click", function() {
  this.classList.toggle("active");
  var dropdownContent = this.nextElementSibling;
  if (dropdownContent.style.display === "block") {
  dropdownContent.style.display = "none";
  } else {
  dropdownContent.style.display = "block";
  }
  });
}
</script>

app/views/channel/memberedit.html.erb
<%= render 'pannel/nav' %>
<div class="main">
  <div class="header">
    <div class="col-md-10" style="font-size:20px;color:pink;padding-top:20px">
      <div class="fa fa-users"> <%= @clickchannel.channel_name %></div><br>
      <%= link_to "Member List", memberedit_path,style:"color:#59b300" %>
    </div>
    <div class="col-md-2", style="float:right;padding-top:30px">      
        <%= link_to "",channelchat_path(:clickchannelid=>session[:clickchannel_id]), class:"fa fa-times-circle", style:"color:pink"%>      
    </div>
  </div>
  <div class="member_edit">
    <div class="user_remove">    
      <div class="col-md-2"><i class="fa fa-fw fa-users"></i><%=@chmembercount%><%="member"%>
      </div>
      <div class="col-md-2" style="color:black">
        <%= link_to "",chmemberinvite_path,class:"fa fa-plus-circle"%>
      </div>
    </div>
    <br>
    <div class="user_remove"> 
     <div class="col-md-2">
          <% @chadmin.each do |click|%>
           <% if (click.user_id== session[:user_id]) && (click.chadmin == true) %>
             <i class="fa fa-fw fa-circle" style="color:green;font-size:18px;"></i>
             <%=click.user_name%>
             <%= link_to "",channelremove_path(removeuser:click.user_id),:method => :delete,class:"fa fa-minus-circle" %>
           <%else%>
            <i class="fa fa-fw fa-circle" style="color:green;font-size:18px;"></i>
            <%=click.user_name%>
            <br>
           <%end%>
         <%end%> 
         <% @chnotadmin.each do |mclick|%>
             <i class="fa fa-fw fa-circle" style="color:green;font-size:18px;"></i>
             <%= mclick.user_name%>
             <%= link_to "",channelremove_path(removeuser:mclick.user_id),:method => :delete,class:"fa fa-minus-circle" %>
            <br>
         <%end%>
        <%= will_paginate @chnotadmin, :page_links => false%>
      </div>     
    </div>
  </div>
  <script>
   /* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
   var dropdown = document.getElementsByClassName("dropdown-btn");
   var i;
   for (i = 0; i < dropdown.length; i++) {
    dropdown[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var dropdownContent = this.nextElementSibling;
    if (dropdownContent.style.display === "block") {
    dropdownContent.style.display = "none";
    } else {
    dropdownContent.style.display = "block";
    }
    });
   }
  </script>
</div>

app/views/channel/pubchannelshow.html.erb
<%= render 'pannel/nav' %>
<div class="main">
<div class="header">
    <div class="col-md-10" style="font-size:20px;color:pink;padding-top:20px">
      <div class="fa fa-firefox"> <%= session[:clickchannel_name]%></div><br>
      <%= link_to "Member List",pubchmember_path, style:"color:#59b300" %>
    </div>
  
    <div class="col-md-2", style="float:right;padding-top:30px">
      
        <%= link_to "@",mention_path,class: "", style:"color:pink" %>
        <%= link_to "",starmessage_path,class: "fa fa-star-o" , style:"color:pink" %>
        <%= link_to "",home_path, class:"fa fa-times-circle", style:"color:pink"%>
      
    </div>
  </div>
    <div class="content">
      <% @chmesg.each do |chmsg|%>   
       
        
          <div class="dropdown-container2">
            <div class="user"><i class="fa fa-fw fa-picture-o"></i>&nbsp;<%= chmsg.user_name %><date style="font-size:18px; padding-left:20px;color:gray;"> <%=  l chmsg.created_at, format: :euro  %><br></date>
            </div>
            <div class="col-md-12 message" style="font-size:16px"> 
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <%= chmsg.chmessage %>
              <%= link_to "","#" , class: "fa fa-trash", style: "color:pink"%>
              <% if @charray.include?(chmsg.chmsg_id)%>
                <%= link_to"","#",class:"fa fa-star",style:"color:pink"%>
              <%end%>
              <% if !@charray.include?(chmsg.chmsg_id)%>
                <%= link_to "","#",class:"fa fa-star-o",style:"color:pink"%>
              <%end%>
              <%if chmsg.count != 0 %>
                <%=chmsg.count%><%= link_to "replies",chreplymsg_path(chclickid:chmsg.chmsg_id),class:"",style:"color:pink"%>
              <%end%>
              <%= link_to "","#", class: "fa fa-comment-o", style: "color:pink"%>
              <br>
            </div>
          </div>
     
        
      <%end%> 
    </div>
     

   
 
  <script>
 $( "#autocomplete-4" ).autocomplete({
      source: $('#autocomplete-4').data('autocomplete-source'),
      position: {
        my: "left bottom",
        at: "left top",
    },
    select: function(event, ui) {
      event.preventDefault();
      this.value = ui.item.label
      $('.memtion_name').val(ui.item.value)
    }
    });
</script>


  <script>
  $('.content').scrollTop($('.content')[0].scrollHeight);
  /* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
  var dropdown = document.getElementsByClassName("dropdown-btn");
  var i;
  
  for (i = 0; i < dropdown.length; i++) {
    dropdown[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var dropdownContent = this.nextElementSibling;
    if (dropdownContent.style.display === "block") {
    dropdownContent.style.display = "none";
    } else {
    dropdownContent.style.display = "block";
    }
    });
  }
  </script>
</div>

 <script language="javascript" type="text/javascript">setTimeout("location.reload();",20000);</script>