config/routes.rb
Rails.application.routes.draw do 
  #yehtetaung start 24/6/2019
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  #yehtetaung end 24/6/2019
  
  #yehtetaung start 26/6/2019
  get '/search', to: 'sessions#search'
  post '/search', to: 'sessions#wsearch'
  #yehtetaung end 1/7/2019
  
  #yehtetaung start 24/6/2019
  root 'static_pages#welcome' 
  #yehtetaung end 24/6/2019

  #yehtetaung start 25/6/2019
  get '/workspacecreate', to: 'static_pages#workspacecreate'
  get '/workspacehome', to: 'static_pages#workspacehome'
  #yehtetaung end 25/6/2019

  #Thinzarthein,SweZinMyat start 24/6/2019
  get '/home', to:'static_pages#home'
  #Thinzarthein,SweZinMyat end 25/6/2019
 
  #SweZinMyat start 5/7/2019
  get '/unread', to: 'static_pages#unread'
  get '/update', to: 'static_pages#update'
  #SweZinMyat end 8/7/2019

  #yehtetaung start 24/6/2019
  get '/signup', to:'users#new'
  post '/signup',to: 'users#create'
  #yehtetaung end 24/6/2019
 
  #yehtetaung start 25/6/2019
  post '/wscreate', to: 'workspace#create'
  get '/wscreate' , to: 'workspace#new'
  #yehtetaung end 25/6/2019
  
  #shinehtetnaung start 25/6/2019
  get '/managemember', to: 'channel#managemember'
  delete '/userremove', to: 'channel#userremove'
  #shinehtetnaung start 28/6/2019

  #Thinzarthein start 17/7/2019
  get '/managechannel', to: 'channel#managechannel'
  delete '/channeldelete', to: 'channel#channeldelete'
  #Thinzarthein end 17/7/2019
  
  #shinehtetnaung start 24/6/2019
  get '/channel', to: 'channel#new'
  post '/channel', to: 'channel#create'
  #shinehtetnaung end 25/6/2019
  
  #Thinzarthein start 26/6/2019
  get '/channelchat', to: 'channel#channelchat'
  get '/memberedit', to: 'channel#memberedit'
  get '/chmemberinvite', to: 'channel#chmemberinvite'
  get '/addchmember', to: 'channel#addchmember'
  delete '/channelremove',to: 'channel#channelremove'
  get '/chreplymsg', to: 'chmsgthread#chreplymsg'
  #Thinzarthein end 3/7/2019
  
  #Thinzarthein,SweZinMyat start 2/7/2019
  post '/chmessage' , to: 'channel#message'
  delete '/chmessagedelete', to:'channel#chmessagedelete'
  #Thinzarthein,SweZinMyat end 4/7/2019
  
  #Eishwezinhtun,yehtetaung  start 25/6/2019
  get '/mention', to: 'channel#mention'
  #Eishwezinhtun,yehtetaung end 12/7/2019
  
  #SweZinMyat start 5/7/2019
  get '/chmsgthread', to: 'chmsgthread#new'
  post '/chthreadinsert', to: 'chmsgthread#chthreadinsert'
  get  '/thread', to: 'threads#new'
  get '/dirmsgthread', to: 'dirmsgthread#new'
  post '/dirthreadinsert', to: 'dirmsgthread#dirthreadinsert'
  #SweZinMyat end 8/7/2019

  #Thinzarthein,SweZinMyat start 26/6/2019
  get  '/dirmsg',  to:'directmessage#new'
  post '/dirmsgcreate', to:'directmessage#create'
  delete '/messagedelete', to:'directmessage#messagedelete'
  #Thinzarthein,SweZinMyat start 1/7/2019

  #Thinzarthein start  10/7/2019
  get '/replymsg', to: 'dirmsgthread#replymsg'
  #Thinzarthein end 10/7/2019
  
  #SweZinMyat start 25/7/2019
  get '/dirmsgstar', to: 'dirmsgstar#new'
  delete '/dirmsgunstar', to: 'dirmsgstar#dirunstar'
  get '/chmsgstar', to: 'chmsgstar#new'
  delete '/chmsgunstar', to: 'chmsgstar#chunstar'
  get '/starmessage', to: 'static_pages#starmessage'
  get '/pubchannelshow', to: 'channel#pubchannelshow'
  get '/pubchmember', to: 'channel#pubchmember'
  #SweZinMyat start 16/7/2019

  #shinehtetnaung start 1/7/2019
  get '/invitations', to:'invitations#invitemember'
  post '/invitations', to:'invitations#create' 
  get '/invite', to: 'joinmembers#new'
  post '/invite', to: 'joinmembers#create' 
  #shinehtetnaung start 8/7/2019

  resources :invitations,only: [:create]
  resources :joinmembers
  
end

app/controllers/directmessage_controller.rb
class DirectmessageController < ApplicationController

  #when click send button,the messages will insert into t_dirmessages table
  def create
    @t_dirmessages = TDirmessage.new
    @t_dirmessages.is_read = 1
    @t_dirmessages.sender_user_id = session[:user_id]
    @t_dirmessages.receiver_user_id = session[:clickuser_id]
    @t_dirmessages.dir_message = params[:dirmessages][:dir_message]
    @t_dirmessages.dirworkspace_id = session[:workspace_id]
    @t_dirmessages.save
    redirect_back(fallback_location: dirmsgcreate_path)
  end

  #To show direct messages
  def new
    @currentname = MUser.find_by("user_id=?", params[:clickuser_id])
    clickuser @currentname
    TDirmessage.where("receiver_user_id=? and sender_user_id=? and dirworkspace_id=?", session[:user_id], params[:clickuser_id], session[:workspace_id]).update_all(is_read: 0)
    main
    @message = TDirmessage.select("m_users.user_id,m_users.user_name,t_dirmessages.dir_message,t_dirmessages.dirmsg_id,t_dirmessages.created_at,t_dirmessages.dirmsg_id,t_dirmessages.count")
                          .joins("join m_users on t_dirmessages.sender_user_id = m_users.user_id")
                          .where("((receiver_user_id=? and sender_user_id=?) || (receiver_user_id=? and sender_user_id=?))", session[:user_id], params[:clickuser_id], params[:clickuser_id], session[:user_id]).order("created_at ASC")
    @dstar = TDirmessage.select("t_directstars.stardimsg_id")
                        .joins("join t_directstars on t_directstars.stardimsg_id=t_dirmessages.dirmsg_id")
                        .where("dirworkspace_id=? and t_directstars.star_userid=?", session[:workspace_id], session[:user_id])
    @array = Array.new
    @dstar.each { |r|
      @array.push(r.stardimsg_id)
    }
    @message.each { |thread|
      @thredcount = HDirmessageReply.select("*")
                                    .joins("join t_dirmessages on t_dirmessages.dirmsg_id=h_dirmessage_replies.dirmsg_id")
                                    .where("h_dirmessage_replies.dirmsg_id=?", thread.dirmsg_id)
      thread.count = @thredcount.size
    }
    #@pubarray = Array.new
    #@m_channel.each { |r|
      #@pubarray.push(r.channel_name)
    #}
    #@public_channel_list = MChannel.select("distinct m_channels.channel_name,m_channels.channel_id")
                                   #.joins("join m_workspaces on m_workspaces.workspace_id = m_channels.workspace_id")
                                   #.where(" m_channels.status=1 and m_workspaces.workspace_id=? and m_channels.user_id!=?", session[:workspace_id], session[:user_id])
    #@dirmsg_original = TDirmessage.select("m_users.user_name,t_dirmessages.count,t_dirmessages.dirmsg_id,t_dirmessages.dir_message,t_dirmessages.created_at")
                                  #.joins("join m_users on m_users.user_id=t_dirmessages.sender_user_id")
                                  #.where("t_dirmessages.dirmsg_id=?", session[:dirthread_id]).order("t_dirmessages.created_at ASC")
    #@dirthread_msg = HDirmessageReply.select("m_users.user_name,h_dirmessage_replies.dirmsg_id,h_dirmessage_replies.dirthread_msg,h_dirmessage_replies.created_at")
                                     #.joins("join m_users on m_users.user_id=h_dirmessage_replies.reply_user_id")
                                     #.where("h_dirmessage_replies.dirmsg_id=? and h_dirmessage_replies.reply_user_id=?", session[:dirthread_id], session[:user_id]).order("h_dirmessage_replies.created_at ASC")
    #@dirmsg_original.each { |thread|
      #@thredcount = HDirmessageReply.select("*")
                                    #.joins("join t_dirmessages on t_dirmessages.dirmsg_id=h_dirmessage_replies.dirmsg_id")
                                    #.where("h_dirmessage_replies.dirmsg_id=?", thread.dirmsg_id)
      #thread.count = @thredcount.size
    #}
  
  end

  #To delete direct messages
  def messagedelete
    TDirmessage.find_by("dirmsg_id=?", params[:messagedelete]).delete
    redirect_back(fallback_location: dirmsgcreate_path)
  end
end

app/helpers/directmessage_helper.rb
module DirectmessageHelper
end

app/views/directmessage/new.html.erb
 <%= render 'pannel/nav' %> 
<div class="main">
  <div class="header",style="margin-top:0px">
    <div class="col-md-10 fa fa-user" style="font-size:20px;color:pink;padding-top:25px">
      <%= @currentname.user_name %>
    </div>
    <div class="col-md-2", style="float:right;padding-top:25px">      
        <%= link_to "",home_path, class:"fa fa-times-circle", style:"color:pink"%>      
    </div>
  </div>
  <div class="content">
   <% @message.each do |message| %>
    <div class="tool">
      <div class="dropdown-container2">      
        <div class="user"><i class="fa fa-fw fa-picture-o"></i>&nbsp;<%= message.user_name %><date style="font-size:18px; padding-left:20px;color:gray;"> <%=  l message.created_at, format: :euro  %><br></date>
        </div>
        <div class="message" style="font-size:16px"> 
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <%= message.dir_message %>
          <%= link_to "",messagedelete_path(messagedelete:message.dirmsg_id),:method => :delete , class: "fa fa-trash", style: "color:pink"%>
          <% if @array.include?(message.dirmsg_id)%>
          <%= link_to"",dirmsgunstar_path(:clickuserid => session[:clickuser_id],:unstarid => message.dirmsg_id),:method => :delete,class:"fa fa-star",style:"color:pink"%>
          <%else%>   
          <%= link_to"",dirmsgstar_path(:clickdstarid => message.dirmsg_id),class:"fa fa-star-o",style:"color:pink"%>
          <%end%>
          <%if message.count != 0 %>
               <%=message.count%><%= link_to "replies",replymsg_path(clickid:message.dirmsg_id),class:"",style:"color:pink"%>
          <%end%>
          <%= link_to "",dirmsgthread_path(dirthread_id:message.dirmsg_id) , class: "fa fa-comment-o", style: "color:pink"%><br>
        </div>
      </div>
    </div>
   <%end%>
  </div>
    <div class="footer">
      <div class="col-md-8 col-md-offset-2", style="margin-top:20px">    
        <%= form_for(:dirmessages, url: dirmsgcreate_path) do |f| %>
        <div class="col-md-10">
        <%= f.text_field :dir_message, class: 'form-control'%> </div> 
        <div class="col-md-2">
        <%= f.submit "Send", class: "btn btn-primary form-control" %></div>
        <% end %>
    </div>
  </div>
  <script>
  $('.content').scrollTop($('.content')[0].scrollHeight);
  /* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
  var dropdown = document.getElementsByClassName("dropdown-btn");
  var i;
  for (i = 0; i < dropdown.length; i++) {
    dropdown[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var dropdownContent = this.nextElementSibling;
    if (dropdownContent.style.display === "block") {
    dropdownContent.style.display = "none";
    } else {
    dropdownContent.style.display = "block";
    }
    });
  }
  </script>
</div>
<script language="javascript" type="text/javascript">setTimeout("location.reload();",20000);</script>