config/routes.rb
Rails.application.routes.draw do 
  #yehtetaung start 24/6/2019
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  #yehtetaung end 24/6/2019
  
  #yehtetaung start 26/6/2019
  get '/search', to: 'sessions#search'
  post '/search', to: 'sessions#wsearch'
  #yehtetaung end 1/7/2019
  
  #yehtetaung start 24/6/2019
  root 'static_pages#welcome' 
  #yehtetaung end 24/6/2019

  #yehtetaung start 25/6/2019
  get '/workspacecreate', to: 'static_pages#workspacecreate'
  get '/workspacehome', to: 'static_pages#workspacehome'
  #yehtetaung end 25/6/2019

  #Thinzarthein,SweZinMyat start 24/6/2019
  get '/home', to:'static_pages#home'
  #Thinzarthein,SweZinMyat end 25/6/2019
 
  #SweZinMyat start 5/7/2019
  get '/unread', to: 'static_pages#unread'
  get '/update', to: 'static_pages#update'
  #SweZinMyat end 8/7/2019

  #yehtetaung start 24/6/2019
  get '/signup', to:'users#new'
  post '/signup',to: 'users#create'
  #yehtetaung end 24/6/2019
 
  #yehtetaung start 25/6/2019
  post '/wscreate', to: 'workspace#create'
  get '/wscreate' , to: 'workspace#new'
  #yehtetaung end 25/6/2019
  
  #shinehtetnaung start 25/6/2019
  get '/managemember', to: 'channel#managemember'
  delete '/userremove', to: 'channel#userremove'
  #shinehtetnaung start 28/6/2019

  #Thinzarthein start 17/7/2019
  get '/managechannel', to: 'channel#managechannel'
  delete '/channeldelete', to: 'channel#channeldelete'
  #Thinzarthein end 17/7/2019
  
  #shinehtetnaung start 24/6/2019
  get '/channel', to: 'channel#new'
  post '/channel', to: 'channel#create'
  #shinehtetnaung end 25/6/2019
  
  #Thinzarthein start 26/6/2019
  get '/channelchat', to: 'channel#channelchat'
  get '/memberedit', to: 'channel#memberedit'
  get '/chmemberinvite', to: 'channel#chmemberinvite'
  get '/addchmember', to: 'channel#addchmember'
  delete '/channelremove',to: 'channel#channelremove'
  get '/chreplymsg', to: 'chmsgthread#chreplymsg'
  #Thinzarthein end 3/7/2019
  
  #Thinzarthein,SweZinMyat start 2/7/2019
  post '/chmessage' , to: 'channel#message'
  delete '/chmessagedelete', to:'channel#chmessagedelete'
  #Thinzarthein,SweZinMyat end 4/7/2019
  
  #Eishwezinhtun,yehtetaung  start 25/6/2019
  get '/mention', to: 'channel#mention'
  #Eishwezinhtun,yehtetaung end 12/7/2019
  
  #SweZinMyat start 5/7/2019
  get '/chmsgthread', to: 'chmsgthread#new'
  post '/chthreadinsert', to: 'chmsgthread#chthreadinsert'
  get  '/thread', to: 'threads#new'
  get '/dirmsgthread', to: 'dirmsgthread#new'
  post '/dirthreadinsert', to: 'dirmsgthread#dirthreadinsert'
  #SweZinMyat end 8/7/2019

  #Thinzarthein,SweZinMyat start 26/6/2019
  get  '/dirmsg',  to:'directmessage#new'
  post '/dirmsgcreate', to:'directmessage#create'
  delete '/messagedelete', to:'directmessage#messagedelete'
  #Thinzarthein,SweZinMyat start 1/7/2019

  #Thinzarthein start  10/7/2019
  get '/replymsg', to: 'dirmsgthread#replymsg'
  #Thinzarthein end 10/7/2019
  
  #SweZinMyat start 25/7/2019
  get '/dirmsgstar', to: 'dirmsgstar#new'
  delete '/dirmsgunstar', to: 'dirmsgstar#dirunstar'
  get '/chmsgstar', to: 'chmsgstar#new'
  delete '/chmsgunstar', to: 'chmsgstar#chunstar'
  get '/starmessage', to: 'static_pages#starmessage'
  get '/pubchannelshow', to: 'channel#pubchannelshow'
  get '/pubchmember', to: 'channel#pubchmember'
  #SweZinMyat start 16/7/2019

  #shinehtetnaung start 1/7/2019
  get '/invitations', to:'invitations#invitemember'
  post '/invitations', to:'invitations#create' 
  get '/invite', to: 'joinmembers#new'
  post '/invite', to: 'joinmembers#create' 
  #shinehtetnaung start 8/7/2019

  resources :invitations,only: [:create]
  resources :joinmembers
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/h_chmessage_reply.rb
class HChmessageReply < ApplicationRecord
end

app/models/h_dirmessage_reply.rb
class HDirmessageReply < ApplicationRecord
end

app/models/h_message_reply.rb
class HMessageReply < ApplicationRecord
end

app/models/m_channel.rb
require 'composite_primary_keys'
class MChannel < ApplicationRecord
    
    self.primary_keys = :workspace_id, :user_id,:channel_id
    validates :channel_name,  presence: true, length: { maximum: 50 }
end

app/models/m_user.rb
class MUser < ApplicationRecord
 
  before_save { self.user_email = user_email.downcase}
  validates :user_name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :user_email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: {case_sensitive: false}

 has_secure_password
 validates :password, presence: true, length: { minimum: 6 }
end

app/models/m_workspace.rb
require 'composite_primary_keys'
class MWorkspace < ApplicationRecord
   
    self.primary_keys = :workspace_id, :user_id
    validates :workspace_name,  presence: true, length: { maximum: 50 }
end

app/models/t_channel_message.rb
class TChannelMessage < ApplicationRecord
    self.primary_keys = :chmsg_id
    validates :chmessage,  presence: true, length: { maximum: 50 }
    has_many :m_users
end

app/models/t_chmsgstar.rb
require 'composite_primary_keys'
class TChmsgstar < ApplicationRecord
     self.primary_keys = :chstar_id,:chmsgstarid,:chstar_userid
end

app/models/t_chunread_message.rb
require 'composite_primary_keys'
class TChunreadMessage < ApplicationRecord
    self.primary_keys = :chmsg_id,:chuser_id,:chunmsg_id
    
end

app/models/t_directstar.rb
require 'composite_primary_keys'
class TDirectstar < ApplicationRecord
     self.primary_keys = :dstar_id,:stardimsg_id,:star_userid
end

app/models/t_dirmessage.rb
class TDirmessage < ApplicationRecord
    self.primary_keys = :dirmsg_id
    validates :dir_message,  presence: true, length: { maximum: 250  }
    has_many :m_users
   
end

app/models/t_mention.rb
class TMention < ApplicationRecord
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channel_helper.rb
module ChannelHelper
end

app/helpers/chmsgstar_helper.rb
module ChmsgstarHelper
end

app/helpers/dirmsgstar_helper.rb
module DirmsgstarHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(m_user)
    session[:user_id] = m_user.user_id
    session[:user_name] = m_user.user_name
  end

  def current(m_work)
    session[:workspace_id] = m_work.workspace_id
    session[:workspace_name] = m_work.workspace_name
    session[:workspace_admin] = m_work.admin
  end

  def channelthread(chthread)
    session[:chthread_id] = chthread.chmsg_id
  end

  def directthread(dirthread)
    session[:dirthread_id] = dirthread.dirmsg_id
  end

  def user_current(user)
    session[:current_id] = user.user_id
    session[:current_name] = user.user_name
  end

  def clickuser(click_user)
    session[:clickuser_id] = click_user.user_id
    session[:clickuser_name] = click_user.user_name
  end

  def clickchannel(click_channel)
    session[:clickchannel_id] = click_channel.channel_id
    session[:clickchannel_name] = click_channel.channel_name
    session[:clickchannel_status] = click_channel.status
  end

  def current_user
    if session[:user_id]
      @current_user ||= MUser.find_by(user_id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/threads_helper.rb
module ThreadsHelper
end

app/views/pannel/_footer.html.erb
<div class="footer">
    <div class="col-md-8 col-md-offset-2", style="margin-top:20px">
        <div class="col-md-10" style="color:black;">
        <div class="input-container">
          <div class="dropup">
            <button class="dropbtn"><%= link_to "@", "#",class: "", style:"color:black" %></button>
            <div class="dropup-content">
            <i style="float:right;">@</i><hr>
            <%= link_to "link 2", "#",class: "", style:"color:black" %>
            <%= link_to "link 3", "#",class: "", style:"color:black" %>
            </div>
          </div>
          <%= text_field :name, class:"input-field",style:"font-size:20px;" %>
          </div>
        </div>
        <div class="col-md-2">
          <%= link_to "Send", "#", class: "btn btn-lg btn-primary btnW" ,style:"float:left;"%>
        </div>
    </div>
  </div>
</div>

app/views/pannel/_nav.html.erb
<div class="sidenav">
  <button class="dropdown-btn">
    <div style="color:pink;font-size:25px">
      <%= session[:workspace_name] %><i class="fa fa-caret-down"></i>
    </div>
    <div>
     <%= session[:user_name]%>
    </div>
   </button>
  <div class="dropdown-container">    
     <% if session[:workspace_admin] == true %>
      <%= link_to "Manage member" , managemember_path %>
     <%end%>     
     <%= link_to "Manage channel" , managechannel_path %>    
     <%= link_to "Sign in other WorkSpace", search_path %>
     <%= link_to "Sign out", logout_path, :method => :delete %>
  </div>
  <br>
   <div class="col-md-12">
    <i class="fa fa-commenting-o" style="float:left;color:white;margin-top:5px;font-size:17px"></i> 
    <%= link_to "Threads", thread_path %>
   </div>
   <div class="col-md-10" ><i class="fa fa-envelope-o" style="float:left;color:white;margin-top:5px;font-size:17px"></i> <%= link_to "Unread",unread_path %></div>
     <%if @totalcount != 0%>
       <div class="col-md-2" style="color:white"><%=@totalcount%> </div> 
     <%end%>
   <div class="text">
     <div class="col-md-10">Channels</div>
     <div class="col-md-2"><%= link_to "",channel_path, class:"fa fa-plus", style:"color:pink" %></a></div>
   </div>   
   <div class="chan1" style="padding-left:0px">
      <div class=""> 
         <% @m_channel.each do |channel| %>
            <div class="col-md-10">
                  <i class="fa fa-users" style="float:left;margin-top:5px;color:white;font-size:13px"></i><%= link_to channel.channel_name,channelchat_path(:clickchannelid => channel.channel_id) , style:"font-size:15px;" %>
            </div>               
            <%if channel.workspace_id != 0%>                  
                  <div class="col-md-2" style="color:white" ><%=channel.workspace_id%></div>
            <%end %>           
         <%end%>            
         <%  @public_channel_list.each do |pubchannel| %>
            <% if !@pubarray.include?(pubchannel.channel_name)%>
              <div class="col-md-12"><i class="fa fa-firefox" style="float:left;margin-top:5px;color:white;font-size:13px" ></i><%= link_to pubchannel.channel_name ,pubchannelshow_path(:clickchannelid => pubchannel.channel_id), style:"font-size:15px;" %></div>
            <%end%>
         <%end%>      
      </div>
   </div>
    &nbsp;
   <div class="col-md-10 text" style="padding-left:10px">MemberList</div>
   <div class="mess">
   <% @curworkuser.each do|user|%>
      <% if user.user_name == session[:user_name] %>
         <div class="col-md-12">
            <i class="fa fa-user" style="float:left;color:white;margin-top:5px;font-size:13px"></i> 
            <%= link_to user.user_name, home_path, style:"font-size:15px;"%>
         </div>
      <%else%>
      <div class="col-md-10" style="color:white">
            <i class="fa fa-user" style="float:left;margin-top:5px;font-size:13px;"></i>
            <%= link_to user.user_name, dirmsg_path(clickuser_id:user.user_id), style:"font-size:15px;"%>
         </div>
       <% if user.user_email != "0"%>
         <div class="col-md-2" style="color:white" ><%=user.user_email%></div>
        <%end%>
       <%end%>
     <%end%>
    </div>
  <br>
  <div class="text">
    <div class="col-md-10">Member_Invite</div>
    <div class="col-md-2"><%= link_to "",invitations_path, class:"fa fa-plus", style:"color:pink" %></div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @m_user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@m_user.errors.count, "error") %>.
    </div>
    <ul>
    <% @m_user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/wshared/_error_messages.html.erb
<% if @m_workspace.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@m_workspace.errors.count, "error") %>.
    </div>
    <ul>
    <% @m_workspace.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>